### ISSUE TITLE
ServerRuntimeError thrown for some big cities

### ISSUE THREAD

**Issue by bagage** [bagage/cadastre-conflation#5]
> 19:56:00 Fail to query overpass: runtime error: Query run out of memory using about 2048 MB of RAM.

Some INSEE that reach this exception: 

* [97301 - Regina (Guyane)](http://www.openstreetmap.org/relation/1663803)
* [13004 - Arles](http://www.openstreetmap.org/relation/73911)

**Comment by RoPP** [comment]
Need more context, is it local overpass instance, api.osm.fr, overpass.de ?

**Comment by bagage** [comment]
According to [wikipedia list](https://fr.wikipedia.org/wiki/Liste_de_communes_fran%C3%A7aises_par_superficie#Communes_les_plus_.C3.A9tendues), this issue comes on both api.osm.fr and overpass.de for cities starting at *Arles* (#26). *Montsinéry-Tonnegrande* (#35) is working OK...

**Comment by bagage** [comment]
Works ok with localhost overpass instance.

**Comment by bagage** [comment]
https://gitlab.com/bagage/cadastre-conflation/issues/5
